# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-12-14 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(max_length=25)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('cover', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('readingTime', models.CharField(blank=True, max_length=10, null=True)),
                ('claps', models.CharField(blank=True, max_length=5, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraped.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraped.Tag'),
        ),
    ]
