# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-12-15 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraped', '0004_article_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='responses',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
