# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-12-15 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraped', '0005_auto_20181216_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='responses',
        ),
    ]
